<HTML>
<b> Giovanna Fernandes Filandia Carvalho,n12,1B</b>
<p>/HTML Olá,sou Giovanna Fernandes.Este é o meu site,criei ele para me aprofundar cada dia mais no ramo da Robótica,e no Github.Irei adquirir conhecimentos
com cada aprendizado que eu conquistar aqui no site. Com os conhecimentos e aprendizados,vou melhorar minha especialidade na computação e na minha vida
profinalizante.
index.html  
